version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: shiny
    image: naturecons/impact
    ports:
      - "3838:3838"
    environment:
      # environmental variables defined in ./.env
      - DATA_DIRECTORY
      - TILE_DIRECTORY
      - R_CONFIG_ACTIVE
    volumes:
      - "${DATA_DIRECTORY}:/appdata"
      - "${TILE_DIRECTORY}:/appdata/tiles"
